name: Rodar Robo Clubmy

on:
  workflow_dispatch:

jobs:
  construir-e-rodar:
    runs-on: ubuntu-latest
    steps:
      - name: Pegar o código
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Peças do Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Instalar Ferramentas do Robô
        run: |
          pip install opencv-python-headless
          pip install easyocr requests supabase beautifulsoup4

      - name: Mandar o robô trabalhar
        run: python meu_robo.py
